/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eStoreSearch;

import org.junit.Test;
import static org.junit.Assert.*;

public class BookTest {

    String VproductID = "012345";
    String Vprice = "25.99";
    String Vyear = "2020";
    String Vdescription = "Intro to JUNIT";
    String Vauthor = "mir ali";
    String Vpublisher = "Undergrad uofg";

    Book classbooktest = new Book(Vprice, Vyear, Vdescription, Vpublisher, Vauthor, VproductID);

  @Test public void authorEmpty(){

    classbooktest = new Book(Vprice, Vyear, Vdescription, Vpublisher, "", VproductID);
  }
  @Test public void PublisherEmpty(){
    
    classbooktest = new Book(Vprice, Vyear, Vdescription, "", Vauthor, VproductID);
  }
  
  @Test public void authorPublisherEmpty(){

    classbooktest = new Book(Vprice, Vyear, Vdescription,"","", VproductID);
  }

  @Test public void testProdcutID(){
    classbooktest.setProductID(VproductID);
    assertEquals("The productID should be 012345",VproductID, classbooktest.getProductID());
  }

  @Test public void testdescription(){
    classbooktest.setDescription(Vdescription);
    assertEquals("The description should be Intro to JUNIT",Vdescription, classbooktest.getDescription());
  }

  @Test public void testpublisher(){
    classbooktest.setPublisher(Vpublisher);
    assertEquals("The publisher should be Undergrad uofg",Vpublisher, classbooktest.getPublisher());
  }

  @Test public void testauthor(){
    classbooktest.setAuthor(Vauthor);
    assertEquals("The author should be mir ali",Vauthor, classbooktest.getAuthor());
  }

  @Test public void testprice(){
    classbooktest.setPrice(Vprice);
    assertEquals("The price should be 25.99",Vprice, classbooktest.getPrice());
  }

  @Test public void EqualityCheck(){
    Book classbooktestcompar = new Book(Vprice, Vyear, Vdescription, Vpublisher, Vauthor, VproductID);
    assertTrue("The Books match", classbooktest.equals(classbooktestcompar));

    classbooktestcompar = new Book(Vprice, Vyear, "C++", "Random",Vauthor, VproductID);
    assertFalse("Different description and publisher", classbooktest.equals(classbooktestcompar));
  }
}
