/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eStoreSearch;

import org.junit.Test;
import static org.junit.Assert.*;

public class EStoreSearchTest {

    String VproductID = "012345";
    String Vprice = "25.99";
    String Vyear = "2020";
    String Vdescription = "Java programming";
    String Vauthor = "mir ali";
    String Vpublisher = "Undergrad uofg";
    String keyWord[] = Vdescription.split("");
    String falsedescription = "Different description";
    String keyWord2[] = falsedescription.split("");
    

    @Test public void matchKeyTest(){

        EStoreSearch testObj = new EStoreSearch();
        assertFalse(testObj.matchKey(keyWord2,Vdescription));
        assertFalse(testObj.matchKey(keyWord,Vdescription));
    }

    @Test public void matchKeyTokenTest(){

        EStoreSearch testObj = new EStoreSearch();
        assertFalse(testObj.matchKey(keyWord2,Vdescription));
        assertFalse(testObj.matchKey(keyWord,Vdescription));
    }

}